### ISSUE TITLE
Context variables extension

### ISSUE THREAD

**Issue by uladz-zubrycki** [linear-b/gitstream#100]
**Describe the bug**

Nothing prevents you from declaring a variable with a same name as the existing gitStream context variables have and one could accidentally do that, yet this isn't a supported thing.

- Allow existing variables' extension,
- Or make it explicitly prohibited.

**To Reproduce**

1. Use `files` context variable in your automation, e.g.
    ```
    {{ files | extensions | match(regex=r/^sql\s*$/) | some }}
    ```
2. Introduce a custom variable named `source`, e.g.
    ```
    source:
      isHotfix: {{ branch.name | includes(regex=r/^hotfix.+$/) }}
    ```
3. gitStream will fail with not that clear error
    ```
    error: TypeError: Cannot read properties of undefined (reading 'map')
        at Context.parseMatchDiffLines (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1412:30)
        at eval (eval at _compile (/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:26:101)
        at _callee3$ (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1265:13)
        at tryCatch (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:97:17)
        at Generator._invoke (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:77:24)
        at Generator.next (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:128:21)
        at asyncGeneratorStep (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:361:24)
        at _next (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:383:9)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    /node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1412
      return !regex ? [] : files.map(function (_ref3) {
    ```

**Expected behavior**

- No errors, core `source` variable is extended with new members from your custom variable,
- Or clear error message saying that one can't use a variable named `source`, as it's a reserved name.

**Comment by BenLloydPearson** [comment]
@uladz-zubrycki welcome, and thanks for reporting this issue! We'll investigate it and let you know when we've implemented a solution for this. In the meantime, any other users who are affected by this bug can 👍  the original post or leave a comment to describe their situation.

**Comment by vim-zz** [comment]
Fixed
