### ISSUE TITLE
UndefinedParserError, no parser can be inferred for 

### ISSUE THREAD

**Issue by Mu-Morsi** [linear-b/gitstream#63]
**Describe the bug**

This happens after it worked perfectly then in action evaluating rules step it gets this error however it pass! 
In the PR it hangs forever in add-reviewers part as queued and gitstream in progress!. 

`{
  e: UndefinedParserError: No parser could be inferred for file: requirements.txt
      at normalize (/node_modules/prettier/index.js:7553:19)
      at formatWithCursor2 (/node_modules/prettier/index.js:8822:50)
      at /node_modules/prettier/index.js:37832:12
      at Object.format (/node_modules/prettier/index.js:37846:12)
      at /node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1356:35
      at Array.every (<anonymous>)
      at Context.parseIsFormattingChange (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1351:56)
      at eval (eval at _compile (/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:50:69)
      at _callee$ (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1161:13)
      at tryCatch (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:97:17)
}`

**Comment by ShakedZrihen** [comment]
Hi!
can you please add more information?
did the action passed (action is green)?
only the add-reviewer stuck at queued?


the error you add here is not a blocker, and not effected on the evaluation of the add-reviewer action :)
