### ISSUE TITLE
Gitstream not reporting that a workflow has failed on a diff error

### ISSUE THREAD

**Issue by Fitz7** [linear-b/gitstream#68]
**Describe the bug**

seeing exactly the same issue as https://github.com/linear-b/gitstream/issues/30

**To Reproduce**

1. The `.cm` automation file
2. The PR URL (as it contains the repo and PR identifiers)
3. Describe your PR relevant content 
4. Add relevant commit SHA

**Expected behavior**

**Screenshots**

**Additional context**

some logs 
```
docker.io/gitstream/rules-engine:latest

> gitstream-rules-engine@1.0.0 start
> node src/app.js

Running tag v1.151
PR: REDACTED/pull/5923
commit: 9791e680a4076d5f3cfc4249c71a10ae58d00d4f
fatal: bad revision 'development-3.0...feature/BLC-14644'
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: cd repo && git diff 'development-3.0'...'feature/BLC-14644' -- .cm/*.cm
fatal: bad revision 'development-3.0...feature/BLC-14644'

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at executeGitCommand (file:///src/utils/git.service.js:15:23)
    at isCmChanged (file:///src/utils/git.service.js:155:18)
    at getCMChanged (file:///src/utils/ruleParser.js:113:21)
    at file:///src/app.js:34:33
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(58) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32,  98,  97, 100,  32,
      114, 101, 118, 105, 115, 105, 111, 110,  32,  39, 100,
      101, 118, 101, 108, 111, 112, 109, 101, 110, 116,  45,
       51,  46,  48,  46,  46,  46, 102, 101,  97, 116, 117,
      114, 101,  47,  66,  76,  67,  45,  49,  52,  54,  52,
       52,  39,  10
    ]
  ],
  pid: 30,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(58) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32,  98,  97, 100,  32,
    114, 101, 118, 105, 115, 105, 111, 110,  32,  39, 100,
    101, 118, 101, 108, 111, 112, 109, 101, 110, 116,  45,
     51,  46,  48,  46,  46,  46, 102, 101,  97, 116, 117,
    114, 101,  47,  66,  76,  67,  45,  49,  52,  54,  52,
     52,  39,  10
  ]
}
```

**Comment by vim-zz** [comment]
@Fitz7 should be fixed now

**Comment by Fitz7** [comment]
@vim-zz I've seen this issue come back maybe. 

Can I where it was fixed? an update to the docker image or the action?

Is there a docker tag I can fix our actions to that is stable?
